In [10]:
import numpy as np
import pandas as pd
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender review education purchased
45   61    Male   Poor        PG       Yes
39   76    Male   Poor        PG        No
36   34  Female   Good        UG       Yes
25   57  Female   Good    School        No
47   38  Female   Good        PG       Yes

In [11]:
df = df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)
X_train

review education
0   Average    School
47     Good        PG
38     Good    School
35     Poor    School
31     Poor    School
6      Good    School
25     Good    School
4   Average        UG
39     Poor        PG
37  Average        PG
8   Average        UG
7      Poor    School
24  Average        PG
16     Poor        UG
41     Good        PG
45     Poor        PG
14     Poor        PG
26     Poor        PG
19     Poor        PG
10     Good        UG
1      Poor        UG
32  Average        UG
49     Good        UG
5   Average    School
34  Average    School
43     Poor        PG
46     Poor        PG
36     Good        UG
20  Average    School
11     Good        UG
33     Good        PG
29  Average        UG
40     Good    School
18     Good    School
12     Poor    School
28     Poor    School
21  Average        PG
42     Good        PG
48     Good        UG
2      Good        PG

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
X_train = oe.transform(X_train)
X_train

array([[1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.]])

In [19]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [20]:
X_train

array([[1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.]])

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [34]:
le.classes_

array([0, 1])

In [36]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train, y_test

(array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0]),
 array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0]))